adding dockerfile and .dockerignore
Psuedoo/LinkHive pull request #28
Opened 2023-09-17 12:37 UTC by shivpateriya

I have added the docker file.
please review it and use the following command to run the docker file.
docker build -t linkhive-app .
docker run -p 3000:3000 linkhive-app

2023-09-17 20:28 UTC, Psuedoo commented
With this change can you also add a docker-compose file? To allow users to just do `docker compose up -d`?

2023-09-17 20:31 UTC, Psuedoo requested changes
Can we also maybe add some instructions in the README.md how to use these changes?

2023-09-17 20:31 UTC, Psuedoo commented on dockerfile
> +CMD ["npm", "run", "dev"]
Not sure that this would be right for production. Might need to be `CMD ["npm", "start"]` or `["npm", "run", "build"]`

2023-09-17 20:31 UTC, Psuedoo commented on dockerfile
> +ENV NEXTAUTH_URL=http://localhost:3000
Along with adding the `docker-compose.yml` these environment vars should be exposed there?

2023-09-17 20:31 UTC, Psuedoo commented on dockerfile
> +RUN npx prisma db seed
Awesome doing this, I didn't even think of needing this. 👍

2023-09-17 21:08 UTC, Psuedoo commented
You might actually need both run and build after looking at this guide: https://levelup.gitconnected.com/dockerize-your-reactjs-app-best-practices-and-examples-10873db0af5f

2023-09-18 07:17 UTC, shivpateriya commented on dockerfile
> +CMD ["npm", "run", "dev"]
When we move to production we will add the mentioned command as we are in just a development phase I use `CMD ["npm", run", "dev"`]

2023-09-18 16:50 UTC, Psuedoo commented on dockerfile
> +CMD ["npm", "run", "dev"]
I see what you're saying but I think the proper way is for us to be production by default. 

Once docker compose is introduced we could implement the use of [docker profiles ](https://docs.docker.com/compose/profiles/). This would allow us to use this Docker container in development. But for now, I think getting this change out for production use is ideal.

2023-09-18 16:54 UTC, Psuedoo commented on dockerfile
> +CMD ["npm", "run", "dev"]
But if you think it's sufficient, @shivpateriya, we can loop back and add it later 😄 Just let me know.

Thanks for helping out with the project.

2023-09-18 19:58 UTC, shivpateriya commented on dockerfile
> +CMD ["npm", "run", "dev"]
Thanks, @Psuedoo  and we can add docker-compose once we have more than 1 container. I am going to update the readme file.

2023-09-20 01:24 UTC, dunnfall commented
this seems super helpful! :)

2023-09-21 04:59 UTC, Psuedoo approved these changes

2023-09-21 05:13 UTC, merged